import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer2";
import {Toaster} from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DoctorDR - ML Diabetic Retinopathy Detection",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        
        <div className="flex flex-col min-h-screen">
        <Navbar/>
        <main className="flex-1 pt-20">
        <Toaster position="top-center"/>
        {children}
        </main>
        <Footer/>
        </div>
      </body>
    </html>
  );
}
